language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
env:
  - DB=sqlite SEQUEL='~> 3.38'
  - DB=sqlite SEQUEL='~> 4.0'
  - DB=mysql SEQUEL='~> 3.38'
  - DB=mysql SEQUEL='~> 4.0'
  - DB=postgres SEQUEL='~> 3.38'
  - DB=postgres SEQUEL='~> 4.0'
gemfile: ci/Gemfile.ci
matrix:
  exclude:
    - rvm: jruby-19mode
      env: DB=sqlite SEQUEL='~> 3.38'
      gemfile: ci/Gemfile.ci
    - rvm: jruby-19mode
      env: DB=sqlite SEQUEL='~> 4.0'
      gemfile: ci/Gemfile.ci
    - rvm: jruby-19mode
      env: DB=mysql SEQUEL='~> 3.38'
      gemfile: ci/Gemfile.ci
    - rvm: jruby-19mode
      env: DB=mysql SEQUEL='~> 4.0'
      gemfile: ci/Gemfile.ci
    - rvm: jruby-19mode
      env: DB=postgres SEQUEL='~> 3.38'
      gemfile: ci/Gemfile.ci
