language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-2.1.1
env:
  - DB=sqlite SEQUEL='~> 3.38'
  - DB=sqlite SEQUEL='~> 4.0'
  - DB=mysql SEQUEL='~> 3.38'
  - DB=mysql SEQUEL='~> 4.0'
  - DB=postgres SEQUEL='~> 3.38'
  - DB=postgres SEQUEL='~> 4.0'
gemfile: ci/Gemfile.ci
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2.1.1
