language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.8
  - 2.3.5
  - 2.4.2
  - jruby-9.1.9.0
env:
  - DB=sqlite SEQUEL='~> 3.38'
  - DB=sqlite SEQUEL='~> 4.0'
  - DB=mysql SEQUEL='~> 3.38'
  - DB=mysql SEQUEL='~> 4.0'
  - DB=postgres SEQUEL='~> 3.38'
  - DB=postgres SEQUEL='~> 4.0'
gemfile: ci/Gemfile.ci
matrix:
  exclude:
    - rvm: jruby-9.1.9.0
      env: DB=sqlite SEQUEL='~> 3.38'
    - rvm: jruby-9.1.9.0
      env: DB=sqlite SEQUEL='~> 4.0'
    - rvm: jruby-9.1.9.0
      env: DB=mysql SEQUEL='~> 3.38'
    - rvm: jruby-9.1.9.0
      env: DB=postgres SEQUEL='~> 3.38'
    - rvm: jruby-9.1.9.0
      env: DB=mysql SEQUEL='~> 4.0'
